### ISSUE TITLE
npm run  dev 命令，项目无法启动

### ISSUE THREAD

**Issue by fantaishao** [dlyt/react-koa-login#1]
你好，在学习react-router v4的过程中，找到你的项目，下载下来，按照你文件 readme里的提示
npm install
npm run dev

启动的时候报错，报错信息如下
![skitch](https://cloud.githubusercontent.com/assets/13132833/26404335/1fda147c-40c4-11e7-964a-0ab758e9e07b.png)

望回复！！

**Comment by dlyt** [comment]
把node升级到7.0以上，我的是v7.6.0。
这个项目你也可以看一下。https://github.com/dlyt/react-koa

**Comment by fantaishao** [comment]
node.js升级到 v.7.10.0了，还是报一样的错误，无法启动

**Comment by dlyt** [comment]
那你把koa-mount换成2.0试试
